spring.application.name=gabungyuk
app.auth.token-secret=change-this-secret-in-production

# ngrok
server.forward-headers-strategy=native

# Port
server.port=${PORT:8080}

# Database - pakai environment variable
spring.datasource.url=jdbc:mariadb://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect