name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /opt/BE-APK-SINERGY
            git pull
            mvn clean package -DskipTests
            pkill -f jar || true
            nohup java -jar target/*.jar > app.log 2>&1 &